import React from 'react';
import Link from 'next/link';
import { FileText } from 'lucide-react';
import NavbarPods from '../../src/components/NavbarPods';
import Footer from '../../src/components/Footer';
import LegalAccordion from '../../src/components/LegalAccordion';

export const metadata = {
  title: 'Terms & Conditions — Converse-AI',
  description: 'Review the terms of service governing your access to and use of the Converse-AI platform.',
  keywords: ['Terms of Service', 'Terms and Conditions', 'Converse-AI Terms', 'User Agreement'],
};

const TERMS_SECTIONS = [
  {
    id: '01',
    number: '01',
    title: 'Acceptance of Terms',
    content: (
      <p>
        By accessing Converse-AI, creating a custom chatbot, or utilizing our chatbot interaction services, you acknowledge that you have read, understood, and agree to these Terms and Conditions in full.
      </p>
    ),
  },
  {
    id: '02',
    number: '02',
    title: 'Use of Converse-AI',
    content: (
      <p>
        Converse-AI provides tools to configure and deploy conversational AI assistants based on business specifications. You agree to use the service solely for lawful purposes and in accordance with these terms.
      </p>
    ),
  },
  {
    id: '03',
    number: '03',
    title: 'User-Provided Information',
    content: (
      <p>
        You are responsible for ensuring that all business descriptions, knowledge inputs, and custom instructions you provide are accurate, lawful, and do not infringe on the intellectual property or legal rights of third parties.
      </p>
    ),
  },
  {
    id: '04',
    number: '04',
    title: 'AI-Generated Responses',
    content: (
      <p>
        Responses generated by Converse-AI assistants are produced by machine learning models based on user inputs. While the system strives for contextual relevance, AI outputs may occasionally contain inaccuracies. Users should review and evaluate responses for sensitive or critical business use cases.
      </p>
    ),
  },
  {
    id: '05',
    number: '05',
    title: 'Acceptable Use',
    content: (
      <p>
        You agree not to use Converse-AI to generate harmful, illegal, harassing, deceptive, fraudulent, or malicious content, nor attempt to reverse-engineer, disrupt, or overload the platform infrastructure.
      </p>
    ),
  },
  {
    id: '06',
    number: '06',
    title: 'Intellectual Property',
    content: (
      <p>
        You retain all rights to the business content and brand materials you provide. Converse-AI retains all ownership, copyright, and intellectual property rights in the platform design, software, interface, and branding.
      </p>
    ),
  },
  {
    id: '07',
    number: '07',
    title: 'Service Availability',
    content: (
      <p>
        We strive to maintain continuous platform availability, but services are provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. Maintenance, updates, or third-party outages may temporarily affect availability.
      </p>
    ),
  },
  {
    id: '08',
    number: '08',
    title: 'Limitation of Liability',
    content: (
      <p>
        To the fullest extent permitted by applicable law, Converse-AI and its operators shall not be liable for any indirect, incidental, or consequential damages resulting from your use of or inability to use the platform or its generated AI outputs.
      </p>
    ),
  },
  {
    id: '09',
    number: '09',
    title: 'Changes to the Service & Terms',
    content: (
      <p>
        We reserve the right to modify, enhance, or discontinue features of the platform, as well as update these Terms and Conditions. Continued use after updates constitutes acceptance of the revised terms.
      </p>
    ),
  },
  {
    id: '10',
    number: '10',
    title: 'Contact Information',
    content: (
      <p>
        If you have any questions or concerns regarding these Terms and Conditions, please contact us at{' '}
        <a
          href="mailto:contact@converse.ai"
          className="text-[#3B82F6] hover:text-[#67E8F9] transition-colors font-mono underline underline-offset-2"
        >
          contact@converse.ai
        </a>
        .
      </p>
    ),
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#06090D] text-[#F1F5F9] flex flex-col selection:bg-[#3B82F6]/35 selection:text-[#F1F5F9] relative overflow-x-hidden">
      
      {/* Ambient Luminous Glow Layers */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden z-0">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] sm:w-[900px] h-[350px] sm:h-[450px] rounded-full bg-gradient-to-b from-[#3B82F6]/10 via-[#06B6D4]/5 to-transparent blur-[140px]" />
        <div className="absolute bottom-1/3 left-10 w-[350px] h-[350px] rounded-full bg-[#06B6D4]/5 blur-[120px]" />
        <div
          className="absolute inset-0 opacity-[0.025]"
          style={{
            backgroundImage: 'radial-gradient(rgba(103, 232, 249, 0.6) 1px, transparent 1px)',
            backgroundSize: '36px 36px',
          }}
        />
      </div>

  

      {/* Main Content Area */}
      <main className="relative z-10 flex-1 w-full max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pt-24 sm:pt-32 md:pt-36 pb-16 sm:pb-24">
        
        {/* Page Header */}
        <header className="text-center max-w-xl mx-auto mb-8 sm:mb-12">
          
          
          <h1 className="text-3xl sm:text-4xl md:text-5xl font-black tracking-tight text-[#F1F5F9] font-sans leading-[1.1] mb-3 sm:mb-4">
            Terms & <span className="text-gradient-primary">Conditions</span>
          </h1>
          
          <p className="text-xs sm:text-sm font-mono text-[#94A3B8]">
            Last Updated: September 2026
          </p>
        </header>

        {/* Intro Statement Card */}
        <div className="mb-6 sm:mb-8 p-5 sm:p-7 rounded-2xl bg-[#0B1117]/85 backdrop-blur-xl border border-[#1E2933] shadow-[0_15px_40px_-15px_rgba(6,9,13,0.9)] relative overflow-hidden">
          <div className="absolute top-0 inset-x-0 h-px bg-gradient-to-r from-transparent via-[#3B82F6]/30 to-transparent pointer-events-none" />
          <p className="text-xs sm:text-sm text-[#94A3B8] leading-relaxed">
            These Terms and Conditions govern your access to and use of Converse-AI. By creating or interacting with chatbots on our website, you agree to comply with and be bound by these terms.
          </p>
        </div>

        {/* Expandable Accordion Sections */}
        <LegalAccordion items={TERMS_SECTIONS} initialOpenId="01" />

      </main>

      {/* Footer */}
      <Footer />

    </div>
  );
}
